[metadata]
name = rascal
version = 0.3.9
license = BSD-3-Clause
license_files = LICENSE
description = A library for automated spectrometer wavelength calibration.
long_description = file: README.md
long_description_content_type = text/markdown
readme = README.md
author = Josh Veitch-Michaelis, Marco C Lam
author_email = j.veitchmichaelis@gmail.com, mlam@roe.ac.uk
maintainer = Josh Veitch-Michaelis, Marco C Lam
maintainer_email = j.veitchmichaelis@gmail.com, mlam@roe.ac.uk
url = https://rascal.readthedocs.io/en/latest/?badge=latest
download_url = https://github.com/jveitchmichaelis/rascal
classifiers =
    License :: OSI Approved :: BSD License
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Operating System :: OS Independent

[options]
zip_safe = False
package_dir=
    =src
packages = find:
include_package_data = True
python_requires = >=3.6
install_requires =
    numpy>=2.2.6
    scipy>=1.15.3
    pynverse>=0.1.4.6
    matplotlib>=3.10.6
    tqdm>=4.67.1
    kaleido>=1.1.0
setup_requires =
    astropy>=6.1.7
    coverage>=7.10.7
    plotly>=6.3.1
    pre-commit>=4.3.0
    psutil>=7.1.0
    pytest>=8.4.2
    pytest-cov>=7.0.0
    requests>=2.32.5
    ruff>=0.14.0

[coverage:run]
relative_files = True

[options.packages.find]
where=src
