# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [main, dev-0.3.X]
  pull_request:
    branches: [main, dev-0.3.X]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
          python-version: ${{ matrix.python-version }}

    - name: Setup venv
      run: uv python install

    - name: Install dependencies
      run: uv sync --all-extras --dev

    - name: Lint with ruff using uv
      run: uv run ruff check --fix

    - name: Test with pytest
      run: |
        uv run pytest -v --disable-warnings -p no:warnings test
    - name: Generate Coveralls reports
      if: startsWith(matrix.os, 'ubuntu')
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        flag-name: Test with pytest

  coveralls_finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
